
defaults: &defaults
  application_name: "STORE"

  items_per_page: 5

  map_initial_lat: 53.525283
  map_initial_lng: -113.525612
  map_initial_zoom: 14

  collection_max_depth: 5

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

  